### ISSUE TITLE
Extracting reusable types to their own interfaces

### ISSUE THREAD

**Issue by BilligsterUser** [cashubtc/cashu-ts#11]
I suggest extracting reusable types to their own interfaces to improve the reusability and maintainability of our codebase.

### Proposed Changes
- Identify common types that are used across multiple components or modules
- Extract these types to their own interfaces
- Update existing code to use the new interfaces

### Additional Information
- This change will improve code reusability and maintainability
- We can avoid duplicating code by sharing interfaces across files

### Tasks
- [x] Identify common types to extract
- [x] Create new interfaces for these types
- [x] Update existing components and modules to use the new interfaces
